_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  announcements_feed: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  business_rules: 0
  camunda: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_split: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dbug: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  eca: 0
  eca_access: 0
  eca_base: 0
  eca_content: 0
  eca_helper: 0
  eca_modeller_bpmn: 0
  eca_queue: 0
  eca_ui: 0
  eca_user: 0
  eca_views: 0
  eca_workflow: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  layout_builder: 0
  layout_discovery: 0
  lb_plus: 0
  link: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search: 0
  shortcut: 0
  smtp: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  typed_data: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_devel: 0
  webform_templates: 0
  webform_ui: 0
  workflow: 0
  workflow_eca: 0
  workflows: 0
  eca_form: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  olivero: 0
  claro: 0
  bootstrap_barrio: 0
  bootstrap_barrio_subtheme: 0
profile: standard
